In [5]:
import numpy as np
row_vect=np.array([[0,3,2],[4,1,1],[0,-2,0]])
print("Row Vectors:\n",row_vect)
x=np.array([[-8],[-1],[4]])
sol=np.linalg.solve(row_vect,x)
print("Solution:\n",sol)
#manually calclated values for coefficients:[0.5,-2,-1]

Row Vectors:
 [[ 0  3  2]
 [ 4  1  1]
 [ 0 -2  0]]
Solution:
 [[ 0.5]
 [-2. ]
 [-1. ]]


In [8]:
#linear equation:
Linear_Combination=row_vect@sol
print("Linear Combination of the given vectors for solution[0.5,-2-1]:\n",Linear_Combination)


Linear Combination of the given vectors for solution[0.5,-2-1]:
 [[-8.]
 [-1.]
 [ 4.]]
