In [1]:
import numpy as np
import sympy

In [2]:
M=np.array([[0,2,1,3],[3,2,8,1],[1,0,0,3],[0,3,2,1]])
print("Given Matrix M:\n",M)
Det=np.round(np.linalg.det(M),2)
print("Determinant of matrix M:\n",Det)

Given Matrix M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant of matrix M:
 -38.0


In [3]:
I=np.eye(4,4,0)
print("Identity Matrix I:\n",I)
prod=M@I
print("Product of M and I:\n",prod)
if np.array_equal(M,prod):
    print("Equal to given matrix M")
else:
    print("Not Equal to given matrix M")

Identity Matrix I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Product of M and I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]
Equal to given matrix M
