In [2]:
import numpy as np

Reversal Matrix Transformation:-

In [7]:
T=np.array([[0,0,1],[0,1,0],[1,0,0]])
print("T:\n",T)
X=np.array([[-1],[0],[1]])
print("X:\n",X)
Y=np.array([[1],[0],[-1]])
print("Y:\n",Y)
LHS1=T.T@(X+Y)
RHS1=(T.T@X)+(T.T@Y)
LHS1,RHS1
if (LHS1==RHS1).all():
    print("First condition is satiesfied\n")
else:
    print("First condition is not satiesfied")
a=2
LHS2=T.T@(a*X)
RHS2=a*(T.T@X)
LHS2,RHS2
if (LHS2==RHS2).all():
    print("Second condition is satiesfied.")
else:
    print("Second condition is not satiesfied.")

T:
 [[0 0 1]
 [0 1 0]
 [1 0 0]]
X:
 [[-1]
 [ 0]
 [ 1]]
Y:
 [[ 1]
 [ 0]
 [-1]]
First condition is satiesfied

Second condition is satiesfied.


Negation Transformation:

In [14]:
T=np.array([[-1,0,0],[0,-1,0],[0,0,-1]])
print("T:\n",T)
X=np.array([[-1],[0],[1]])
print("X:\n",X)
Y=T@X
print("Vector after transformation:\n",Y)

T:
 [[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
X:
 [[-1]
 [ 0]
 [ 1]]
Vector after transformation:
 [[ 1]
 [ 0]
 [-1]]


Scaling Transformation:

In [15]:
x=np.array([3,5,7])
print("x:\n",x)
a=3
print("Scaling Factor:",a)
I=np.eye(3,3,0)
A=a*I
print("A:\n",A)
y=A@x
print("Vector after transformation:\n",y)

L2x=np.linalg.norm(x,2)
L2y=np.linalg.norm(y,2)
if L2y==3*L2x:
    print("Matrix A is scaling transformation matrix")
else:
    print("no")

x:
 [3 5 7]
Scaling Factor: 3
A:
 [[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]
Vector after transformation:
 [ 9. 15. 21.]
Matrix A is scaling transformation matrix


Reflection Transformation: (theta= angle of reflection line from horizontal line)

In [46]:
A=np.array([["cos(2*theta)","sin(2*theta)"],["sin(2*theta)","-cos(2*theta)"]])
print("Tranformation Matrix A:\n",A)
print()
def refl(theta,x):
    a=round(np.cos(np.radians(2*theta)))
    b=round(np.sin(np.radians(2*theta)))
    c=round(np.sin(np.radians(2*theta)))
    d=-round(np.cos(np.radians(2*theta)))
    A=np.array([[a,b],[c,d]])
    print(A)
    y=A@x
    print("Vector after transformation:\n",y)
    print()
    return
x=np.array([2,3])
print("Along x-axis: theta=0")
refl(0,x)
print("Along y-axis: theta=90")
refl(90,x)
print("Along origine line: theta=45")
refl(45,x)


Tranformation Matrix A:
 [['cos(2*theta)' 'sin(2*theta)']
 ['sin(2*theta)' '-cos(2*theta)']]

Along x-axis: theta=0
[[ 1  0]
 [ 0 -1]]
Vector after transformation:
 [ 2 -3]

Along y-axis: theta=90
[[-1  0]
 [ 0  1]]
Vector after transformation:
 [-2  3]

Along origine line: theta=45
[[0 1]
 [1 0]]
Vector after transformation:
 [3 2]



Shearing Transformation:

In [54]:
#share factor (m)
m=2
print("Horizontal Shearing(x-axis):")
A=np.array([[1,'m'],[0,1]])
print(A)
A=np.array([[1,m],[0,1]])
x=np.array([[0,2],[0,4]])
y=A@x
print("Vector after transformation:\n",y)
print()

print("Verticle Shearing(y-axis):")
A=np.array([[1,0],['m',1]])
print(A)
A=np.array([[1,0],[m,1]])
x=np.array([[2,4],[0,4]])
y=A@x
print("Vector after transformation:\n",y)

Horizontal Shearing(x-axis):
[['1' 'm']
 ['0' '1']]
Vector after transformation:
 [[ 0 10]
 [ 0  4]]

Verticle Shearing(y-axis):
[['1' '0']
 ['m' '1']]
Vector after transformation:
 [[ 2  4]
 [ 4 12]]


Rotation ransformation:

In [57]:
A=np.array([["cos(theta)","-sin(theta)"],["sin(theta)","cos(theta)"]])
print("Tranformation Matrix A:\n",A)
print()
x=np.array([2,3])
theta=90     #angle of rotation(aniclockwise +ve)
a=round(np.cos(np.radians(theta)))
b=-round(np.sin(np.radians(theta)))
c=round(np.sin(np.radians(theta)))
d=round(np.cos(np.radians(theta)))
A=np.array([[a,b],[c,d]])
print(A)
print()
y=A@x
print("Vector after transformation:\n",y)
print()

Tranformation Matrix A:
 [['cos(theta)' '-sin(theta)']
 ['sin(theta)' 'cos(theta)']]

[[ 0 -1]
 [ 1  0]]

Vector after transformation:
 [-3  2]

